---
version: '3'
services:
  steve-auth-api:
    image: steve-auth-api:latest
    container_name: steve-auth-api
    build:
      context: ./
      dockerfile: ./Dockerfile
    env_file:
      - .google_credentials
    environment:
      SERVER_PORT: "8080"
      GOOGLE_REDIRECT_URI: "http://127.0.0.1:8080/auth"
      GOOGLE_REQUEST_URL: "https://oauth2.googleapis.com/token"
      MONGO_URI: mongodb://mongo:27017
      MONGO_USER: root
      MONGO_PASSWORD: root
      MONGO_DATABASE: auth
      MONGO_COLLECTION: credentials
    ports:
      - 8080:8080
    links:
      - mongo
  mongo:
    image: mongo:4.2.3
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: "root"
      MONGO_INITDB_ROOT_PASSWORD: "root"
    ports:
      - 27017:27017
